import * as fs from 'node:fs';
import * as ts from 'typescript';

export const VIRTUAL_MODULE_ID = 'virtual:sveltekit-actionbus/events';
export const RESOLVED_VIRTUAL_ID = `\0${VIRTUAL_MODULE_ID}`;

export interface ActionChannelMetadata {
	pattern: string;
	regExpSource: string;
	events: string[];
}

export interface GenerateActionMetadataResult {
	channels: ActionChannelMetadata[];
	sourceCode: string;
}

export function generateActionMetadata(appDtsPath: string): GenerateActionMetadataResult {
	const source = fs.readFileSync(appDtsPath, 'utf-8');
	const sourceFile = ts.createSourceFile(
		'app.d.ts',
		source,
		ts.ScriptTarget.Latest,
		false,
		ts.ScriptKind.TS
	);
	const channels = extractActionChannels(sourceFile);

	const sourceCode = [
		'// Auto-generated by sveltekit-actionbus vite plugin',
		'// Regenerated on every app.d.ts change - do not commit',
		'',
		`export const ACTIONBUS_METADATA = ${JSON.stringify({ channels }, null, 2)};`,
		'',
		'export const ACTION_CHANNELS = ACTIONBUS_METADATA.channels;',
		'',
		'export function findActionChannel(channel) {',
		'  return ACTION_CHANNELS.find((entry) => new RegExp(entry.regExpSource).test(channel));',
		'}',
		'',
		'export function isValidActionChannel(channel) {',
		"  return typeof channel === 'string' && !!findActionChannel(channel);",
		'}',
		'',
		'export function isValidActionEventForChannel(channel, event) {',
		"  if (!event || typeof event !== 'object' || typeof event.type !== 'string') return false;",
		'  const entry = findActionChannel(channel);',
		'  return !!entry && entry.events.includes(event.type);',
		'}',
		''
	].join('\n');

	return { channels, sourceCode };
}

function extractActionChannels(sourceFile: ts.SourceFile): ActionChannelMetadata[] {
	const channels: ActionChannelMetadata[] = [];

	function visit(node: ts.Node): void {
		if (ts.isInterfaceDeclaration(node) && node.name.text === 'ActionEvents') {
			for (const member of node.members) {
				if (!ts.isPropertySignature(member) || !member.name || !member.type) continue;

				const pattern = readPropertyName(member.name, sourceFile);
				if (!pattern) continue;

				const events = extractNestedEventNames(member.type, sourceFile);
				channels.push({
					pattern,
					regExpSource: patternToRegExpSource(pattern),
					events
				});
			}
		}
		ts.forEachChild(node, visit);
	}

	visit(sourceFile);
	return channels;
}

function extractNestedEventNames(type: ts.TypeNode, sourceFile: ts.SourceFile): string[] {
	if (!ts.isTypeLiteralNode(type)) return [];

	return type.members
		.map((member) => {
			if (!ts.isPropertySignature(member) || !member.name) return undefined;
			return readPropertyName(member.name, sourceFile);
		})
		.filter((name): name is string => !!name);
}

function readPropertyName(name: ts.PropertyName, sourceFile: ts.SourceFile): string | undefined {
	if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) {
		return name.text;
	}

	const text = name.getText(sourceFile).replace(/^['"`]|['"`]$/g, '');
	return text || undefined;
}

function patternToRegExpSource(pattern: string): string {
	const placeholder = '\0ACTIONBUS_STRING\0';
	const withPlaceholder = pattern.replaceAll('${string}', placeholder);
	const escaped = withPlaceholder.replace(/[|\\{}()[\]^$+*?.]/g, '\\$&');
	return `^${escaped.replaceAll(placeholder, '.+')}$`;
}
